"""
AI Pipeline SQLAlchemy Models
Implements document metadata, extracted entities, and pgvector embeddings.
"""

from datetime import UTC, datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.models.base import Base, UUIDPrimaryKeyMixin

METADATA_SOURCES = ["manual", "ai_extracted", "system"]

ENTITY_TYPES = [
    "person",
    "organization",
    "location",
    "date",
    "law_section",
    "case_number",
    "fir_number",
    "police_station",
    "evidence_ref",
    "phone_number",
    "vehicle_number",
]


class DocumentMetadata(Base, UUIDPrimaryKeyMixin):
    """
    Key-value structured metadata associated with a legal document.
    Can be AI-extracted or manually populated and verified by officers.
    """

    __tablename__ = "document_metadata"
    __table_args__ = (
        CheckConstraint(
            f"source IN ({', '.join(f"'{s}'" for s in METADATA_SOURCES)})",
            name="chk_document_metadata_source",
        ),
        Index("ix_document_metadata_doc_key", "document_id", "key"),
        Index("ix_document_metadata_source", "source"),
    )

    document_id = Column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    key = Column(String(255), nullable=False)
    value = Column(Text, nullable=False)
    source = Column(String(50), nullable=False, default="ai_extracted")
    confidence = Column(Float, nullable=True)
    verified_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    verified_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False)

    # Relationships
    document = relationship("Document", foreign_keys=[document_id], back_populates="metadata_entries")
    verifier = relationship("User", foreign_keys=[verified_by])


class ExtractedEntity(Base, UUIDPrimaryKeyMixin):
    """
    Domain-specific legal entities extracted from document text by NLP/LLM pipeline.
    Supports human-in-the-loop officer verification.
    """

    __tablename__ = "extracted_entities"
    __table_args__ = (
        CheckConstraint(
            f"entity_type IN ({', '.join(f"'{t}'" for t in ENTITY_TYPES)})",
            name="chk_extracted_entity_type",
        ),
        Index("ix_extracted_entities_document_id", "document_id"),
        Index("ix_extracted_entities_type", "entity_type"),
        Index("ix_extracted_entities_type_value", "entity_type", "entity_value"),
    )

    document_id = Column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    entity_type = Column(String(100), nullable=False)
    entity_value = Column(Text, nullable=False)
    confidence = Column(Float, nullable=True)
    start_offset = Column(Integer, nullable=True)
    end_offset = Column(Integer, nullable=True)
    source = Column(String(50), nullable=False, default="ai")
    verified = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False)

    # Relationships
    document = relationship("Document", foreign_keys=[document_id], back_populates="entities")


class DocumentEmbedding(Base, UUIDPrimaryKeyMixin):
    """
    Dense text vector embeddings for semantic search and RAG retrieval.
    768-dimensional embeddings generated by text-embedding-004.
    Indexed with HNSW for fast cosine similarity search.
    """

    __tablename__ = "document_embeddings"
    __table_args__ = (
        Index("ix_document_embeddings_case_id", "case_id"),
        Index("ix_document_embeddings_doc_chunk", "document_id", "chunk_index"),
        Index("ix_document_embeddings_version_id", "version_id"),
        Index("ix_document_embeddings_is_searchable", "is_searchable"),
        Index("ix_document_embeddings_chunk_id", "chunk_id"),
        UniqueConstraint("version_id", "chunk_index", "model_name", name="uq_version_chunk_model"),
        Index(
            "ix_document_embeddings_vector",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    document_id = Column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    case_id = Column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
    )
    version_id = Column(
        UUID(as_uuid=True),
        ForeignKey("document_versions.id", ondelete="CASCADE"),
        nullable=True,
    )
    chunk_id = Column(String(120), nullable=True)
    chunk_index = Column(Integer, nullable=False)
    chunk_text = Column(Text, nullable=False)
    embedding = Column(Vector(768), nullable=False)
    model_name = Column(String(100), nullable=False, default="models/text-embedding-004")
    vector_dimensions = Column(Integer, nullable=False, default=768)
    is_searchable = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False)

    # Relationships
    document = relationship("Document", foreign_keys=[document_id], back_populates="embeddings")
    case = relationship("Case", foreign_keys=[case_id])
    version = relationship("DocumentVersion", foreign_keys=[version_id])

