"""
Search & RAG Schemas for Phase 7
Defines request and response models for semantic, keyword, hybrid RRF search,
and citation-grounded RAG question answering.
"""

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

STATUTORY_LEGAL_DISCLAIMER = (
    "Automated Legal Intelligence Disclaimer: This response was generated by DOCSHIELD AI "
    "from indexed case documents. It does not constitute formal legal counsel or investigative findings. "
    "All cited sources must be independently verified by authorized personnel before court submission."
)


class SearchSemanticRequest(BaseModel):
    """Request for dense vector cosine similarity search."""
    query: str = Field(min_length=1, max_length=500, description="Search query string")
    case_id: UUID | None = Field(default=None, description="Optional case boundary filter")
    top_k: int = Field(default=10, ge=1, le=50, description="Max results to return")
    min_similarity: float = Field(default=0.4, ge=0.0, le=1.0, description="Cosine similarity threshold")


class SearchHybridRequest(BaseModel):
    """Request for Reciprocal Rank Fusion (RRF) hybrid search."""
    query: str = Field(min_length=1, max_length=500, description="Search query string")
    case_id: UUID | None = Field(default=None, description="Optional case boundary filter")
    top_k: int = Field(default=10, ge=1, le=50, description="Max results to return")
    alpha: float = Field(
        default=0.7,
        ge=0.0,
        le=1.0,
        description="Weight for semantic vector search (1 - alpha for keyword)",
    )


class SearchKeywordRequest(BaseModel):
    """Request for PostgreSQL keyword search."""
    query: str = Field(min_length=1, max_length=500, description="Search query string")
    case_id: UUID | None = Field(default=None, description="Optional case boundary filter")
    top_k: int = Field(default=10, ge=1, le=50, description="Max results to return")


class SearchResultItem(BaseModel):
    """Single ranked search match across document chunks."""
    model_config = ConfigDict(from_attributes=True)

    chunk_id: str = Field(description="Stable source identifier, e.g. DOC-12345678-V1-C0")
    document_id: UUID
    case_id: UUID
    version_id: UUID | None = None
    version_number: int = 1
    document_title: str
    document_type: str
    chunk_index: int
    chunk_text: str
    similarity: float = Field(ge=0.0, le=1.0, description="Normalized similarity or relevance score")
    rrf_score: float | None = None
    search_type: str = "semantic"


class SearchResponse(BaseModel):
    """Unified search response payload."""
    query: str
    case_id: UUID | None = None
    search_type: str
    total_results: int
    results: list[SearchResultItem]


class SearchAskRequest(BaseModel):
    """Request to generate grounded answers using RAG over authorized documents."""
    question: str = Field(min_length=2, max_length=1000, description="Investigative question")
    case_id: UUID | None = Field(default=None, description="Optional case boundary filter")
    top_k: int = Field(default=5, ge=1, le=15, description="Max context chunks to retrieve")


class CitationItem(BaseModel):
    """Verified citation grounding an answer."""
    chunk_id: str
    document_id: UUID
    document_title: str
    document_type: str
    version_number: int
    snippet: str


class SearchAskResponse(BaseModel):
    """Grounded RAG answer with validated citations and mandatory statutory disclaimer."""
    question: str
    case_id: UUID | None = None
    answer: str
    citations: list[CitationItem]
    unverified_citations_removed: int = 0
    ai_generated: bool = True
    disclaimer: str = STATUTORY_LEGAL_DISCLAIMER


class SearchStatusResponse(BaseModel):
    """Index statistics for user-accessible cases."""
    total_embeddings: int
    searchable_embeddings: int
    indexed_documents_count: int
    model_name: str
    vector_dimensions: int

